# Generated by Django 3.1 on 2020-08-31 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Companies',
        ),
        migrations.RenameModel(
            old_name='Email',
            new_name='Emails',
        ),
        migrations.RenameModel(
            old_name='Name',
            new_name='Names',
        ),
    ]
