# Generated by Django 3.1 on 2020-08-31 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200831_0758'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emails',
            new_name='Email',
        ),
        migrations.RenameModel(
            old_name='Companies',
            new_name='Employer',
        ),
        migrations.RenameModel(
            old_name='Names',
            new_name='Name',
        ),
    ]
