# Generated by Django 3.1 on 2020-08-31 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200831_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='maritalstatus',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employer'),
        ),
        migrations.AddField(
            model_name='person',
            name='employee',
            field=models.ManyToManyField(blank=True, to='main.Employer'),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='status',
            field=models.TextField(choices=[('M', 'married'), ('D', 'divorced'), ('S', 'separated'), ('SN', 'single')], null=True),
        ),
    ]
