# Generated by Django 3.1 on 2020-08-31 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200831_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maritalstatus',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.person'),
        ),
    ]
