# Generated by Django 3.1 on 2020-09-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200831_1652'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employer',
            new_name='Company_Name',
        ),
        migrations.RenameModel(
            old_name='Person',
            new_name='Employee',
        ),
        migrations.AlterModelOptions(
            name='company_name',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='status',
            field=models.TextField(choices=[('M', 'Married'), ('D', 'Divorced'), ('S', 'Separated'), ('SN', 'Single')], null=True),
        ),
    ]
