# Generated by Django 3.1 on 2020-09-01 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200901_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.CharField(max_length=10)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
            ],
            options={
                'verbose_name_plural': 'Salaries',
            },
        ),
    ]
