# Generated by Django 3.1 on 2020-09-01 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_salary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company_Name',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='company',
        ),
    ]
