# Generated by Django 3.1 on 2020-09-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200901_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='currency',
            field=models.TextField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('JPY', 'JPY'), ('GBP', 'GBP'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('NZD', 'NZD')], null=True),
        ),
    ]
