# Generated by Django 3.1 on 2020-09-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_salary_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='currency',
            field=models.TextField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('JPY', 'JPY'), ('GBP', 'GBP'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('NZD', 'NZD')], null=True),
        ),
    ]
