# Generated by Django 3.1 on 2020-09-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='Enter valid email.', max_length=254),
        ),
    ]
