# Generated by Django 3.1 on 2020-09-10 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200903_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee',
            new_name='company_name',
        ),
    ]
