# Generated by Django 3.1 on 2020-09-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_employee_pan1'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.TextField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], null=True),
        ),
    ]
