# Generated by Django 3.1 on 2020-09-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.TextField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('NA', 'Decline to State')], null=True),
        ),
    ]
