# Generated by Django 3.1 on 2020-09-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200911_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address_1',
            field=models.CharField(default='Address Line 1', max_length=1024),
        ),
        migrations.AddField(
            model_name='employee',
            name='address_2',
            field=models.CharField(default='Address Line 2', max_length=1024),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.TextField(default='City'),
        ),
        migrations.AddField(
            model_name='employee',
            name='country',
            field=models.TextField(default='Country'),
        ),
        migrations.AddField(
            model_name='employee',
            name='pin_code',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='state',
            field=models.TextField(default='State'),
        ),
    ]
