# Generated by Django 3.1 on 2020-09-11 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200911_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='pan1',
            new_name='pan',
        ),
    ]
