# Generated by Django 3.1 on 2020-09-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200911_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='currency',
            field=models.TextField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('JPY', 'JPY'), ('GBP', 'GBP'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('NZD', 'NZD')], null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
